behaviors:
  Player:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 3.0e-4
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      deterministic: true
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          deterministic: true
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 10000