behaviors:
  Player:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 1.5e-4
      beta: 3.0e-4
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          deterministic: false
    max_steps: 10000000
    time_horizon: 128
    threaded: true
    summary_freq: 10000